name: Test stuff

on:
  workflow_dispatch:

defaults:
  run:
    shell: pwsh

jobs:
  trigger-info:
    name: Trigger info
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
    - name: Dump github context for debug purposes
      env:
        GITHUB_CONTEXT: ${{ toJSON(github) }}
      run: $env:GITHUB_CONTEXT
    - name: Trigger info
      run: |
        Write-Output "::notice::This worklfow was triggered by a 'workflow_run' from '${{ github.event.workflow_run.name }}'."

  test:
    name: test
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Debug
      run: |
        Write-Output $Env:ACTIONS_RUNTIME_URL
        Write-Output $Env:GITHUB_RUN_ID
    - name: Run share jobs data
      uses: ./
      with:
        data: |
          name: George Washington
          age: 89
          height_in_inches: 5.75
          addresses:
            home:
              street: 400 Mockingbird Lane
              city: Louaryland
              state: Hawidaho
              zip: 99970
              list:
              - first
              - second
              - third

  test2:
    name: test 2
    # permissions:
    #   contents: read
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: pwsh list env
      run: |
        dir env:
    - name: unbunt list env
      shell: bash
      run: env
    - name: bash echo
      shell: bash
      run: |
          echo "ACTIONS_RUNTIME_URL: $ACTIONS_RUNTIME_URL"
          echo "GITHUB_RUN_ID: $GITHUB_RUN_ID"
          echo "ACTIONS_RUNTIME_TOKEN: $ACTIONS_RUNTIME_TOKEN"
    - name: Debug 2
      env:
        SOME_URL: ${{ env.ACTIONS_RUNTIME_URL }}
        SOME_URL_2: test
      run: |
        Write-Output $Env:SOME_URL
        Write-Output $Env:SOME_URL_2
    - name: Debug
      run: |
        Write-Output $Env:ACTIONS_RUNTIME_URL
        Write-Output $Env:GITHUB_RUN_ID
        "hi" > test.txt
    - name: Upload test
      uses: actions/upload-artifact@v3
      with:
        name: my-test
        path: ./test.txt