name: Test GitHub action - share data on current workflow

on:
  workflow_dispatch:

defaults:
  run:
    shell: pwsh

jobs:
  trigger-info:
    name: Trigger info
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
    - name: Dump github context for debug purposes
      env:
        GITHUB_CONTEXT: ${{ toJSON(github) }}
      run: $env:GITHUB_CONTEXT
    - name: Trigger info
      run: |
        Write-Output "::notice::This worklfow was triggered by a 'workflow_run' from '${{ github.event.workflow_run.name }}'."

  share-job-github-step-json-output:
    name: share with github-step-json output
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Run set-data command
      id: set
      uses: ./
      with:
        command: set-data
        artifact-name: from-set-with-github-step-json-output
        data: |
          name: George Washington
          age: 89
          height_in_inches: 5.75
          addresses:
            home:
              street: |
                400 Mockingbird Lane
                address line 2
              city: Louaryland
              state: Hawidaho
              zip: 99970
              list:
              - first
              - second
              - third
    - name: Dump outputs from previous step
      env:
        STEP_OUTPUT: ${{ toJSON(steps.set.outputs) }}
      run: $env:STEP_OUTPUT
    - name: Verify set-data command output
      run: |
        if('${{ steps.set.outputs.name }}' -eq 'George Washington'
          && '${{ steps.set.outputs.age }}' -eq '89'
          && '${{ steps.set.outputs.height_in_inches }}' -eq '5.75'
          && '${{ steps.set.outputs.addresses.home.street }}' -eq '400 Mockingbird Lane\naddress line 2'
          && '${{ steps.set.outputs.addresses.home.city }}' -eq 'Louaryland'
          && '${{ steps.set.outputs.addresses.home.state }}' -eq 'Hawidaho'
          && '${{ steps.set.outputs.addresses.home.zip }}' -eq '99970'
          && '${{ steps.set.outputs.addresses.home.list_0_ }}' -eq 'first'
          && '${{ steps.set.outputs.addresses.home.list_1_ }}' -eq 'second'
          && '${{ steps.set.outputs.addresses.home.list_2_ }}' -eq 'third')
        {
          Write-Output "Action produced expected output values."
          Exit 0
        }

        Write-Output "::error::Action didn't produce expected github-step-json output."
        Exit 1


  share-job-strict-json-output:
    name: share with strict-json output
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Run share jobs data
      id: set
      uses: ./
      with:
        command: set-data
        artifact-name: from-set-with-strict-json-output
        output: strict-json
        data: |
          name: George Washington
          age: 89
          height_in_inches: 5.75
          addresses:
            home:
              street: |
                400 Mockingbird Lane
                address line 2
              city: Louaryland
              state: Hawidaho
              zip: 99970
              list:
              - first
              - second
              - third
    - name: Dump outputs from previous step
      env:
        STEP_OUTPUT: ${{ toJSON(steps.set.outputs) }}
      run: $env:STEP_OUTPUT

  share-job-none-output:
    name: share with none output
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Run share jobs data
      id: set
      uses: ./
      with:
        command: set-data
        output: none
        data: |
          name: George Washington
          artifact-name: from-set-with-none-output
          age: 89
          height_in_inches: 5.75
          addresses:
            home:
              street: |
                400 Mockingbird Lane
                address line 2
              city: Louaryland
              state: Hawidaho
              zip: 99970
              list:
              - first
              - second
              - third
    - name: Dump outputs from previous step
      env:
        STEP_OUTPUT: ${{ toJSON(steps.set.outputs) }}
      run: $env:STEP_OUTPUT

  read-job:
    name: read
    permissions:
      contents: read
    runs-on: ubuntu-latest
    needs: [share-job-github-step-json-output]
    steps:
    - uses: actions/checkout@v3
    - name: Run read jobs data
      id: read
      uses: ./
      with:
        command: read-data-current-workflow
        artifact-name: from-set-with-github-step-json-output
    - name: Dump outputs from previous step
      env:
        STEP_OUTPUT: ${{ toJSON(steps.read.outputs) }}
      run: $env:STEP_OUTPUT
    - name: read output
      run: |
        Write-Output '${{ steps.read.outputs.name }}'
        Write-Output '${{ steps.read.outputs.age }}'
        Write-Output '${{ steps.read.outputs.addresses_home_street }}'
        Write-Output '${{ steps.read.outputs.addresses_home_list_0_ }}'
