name: Test stuff

on:
  workflow_dispatch:

defaults:
  run:
    shell: pwsh

jobs:
  trigger-info:
    name: Trigger info
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
    - name: Dump github context for debug purposes
      env:
        GITHUB_CONTEXT: ${{ toJSON(github) }}
      run: $env:GITHUB_CONTEXT
    - name: Trigger info
      run: |
        Write-Output "::notice::This worklfow was triggered by a 'workflow_run' from '${{ github.event.workflow_run.name }}'."

  share-job:
    name: share
    # permissions:
    #   contents: read
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Run share jobs data
      uses: ./
      with:
        command: set-data
        data: |
          name: George Washington
          age: 89
          height_in_inches: 5.75
          addresses:
            home:
              street: |
                400 Mockingbird Lane
                address line 2
              city: Louaryland
              state: Hawidaho
              zip: 99970
              list:
              - first
              - second
              - third

  read-job:
    name: read
    # permissions:
    #   contents: read
    runs-on: ubuntu-latest
    needs: [share-job]
    steps:
    - uses: actions/checkout@v3
    - name: Run read jobs data
      id: read
      uses: ./
      with:
        command: read-data-current-workflow
    - name: Dump outputs from previous step
      shell: pwsh
      env:
        STEP_OUTPUT: ${{ toJSON(steps.read.outputs) }}
      run: $env:STEP_OUTPUT
    - name: read output
      shell: pwsh
      run: |
        Write-Output ${{ fromJson(steps.read.outputs.data).name }}
        Write-Output ${{ fromJson(steps.read.outputs.data).addresses.home.street }}
        Write-Output ${{ fromJson(steps.read.outputs.data).addresses.home.list[0] }}

        Write-Output '${{ steps.read.outputs.data.name }}'
        Write-Output '${{ steps.read.outputs.data.age }}'
        Write-Output '${{ steps.read.outputs.data.addresses.home.street }}'
        Write-Output '${{ steps.read.outputs.data.addresses.home.list[0] }}'
    # - name: ls download
    #   run: |
    #     ls -R
    # - name: cat download
    #   run: |
    #     cat test.txt

  # test2:
  #   name: test 2
  #   # permissions:
  #   #   contents: read
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: actions/checkout@v3
  #   - name: pwsh list env
  #     run: |
  #       dir env:
  #   - name: unbunt list env
  #     shell: bash
  #     run: env
  #   - name: bash echo
  #     shell: bash
  #     run: |
  #         echo "ACTIONS_RUNTIME_URL: $ACTIONS_RUNTIME_URL"
  #         echo "GITHUB_RUN_ID: $GITHUB_RUN_ID"
  #         echo "ACTIONS_RUNTIME_TOKEN: $ACTIONS_RUNTIME_TOKEN"
  #   - uses: actions/github-script@v6.1.0
  #     with:
  #       script: |
  #         const runtimeUrl = process.env['ACTIONS_RUNTIME_URL']
  #         console.log(runtimeUrl)
  #   - name: Debug 2
  #     env:
  #       SOME_URL: ${{ env.ACTIONS_RUNTIME_URL }}
  #       SOME_URL_2: test
  #     run: |
  #       Write-Output $Env:SOME_URL
  #       Write-Output $Env:SOME_URL_2
  #   - name: Debug
  #     run: |
  #       Write-Output $Env:ACTIONS_RUNTIME_URL
  #       Write-Output $Env:GITHUB_RUN_ID
  #       "hi" > test.txt
  #   - name: Upload test
  #     uses: actions/upload-artifact@v3
  #     with:
  #       name: my-test
  #       path: ./test.txt